Repository unboxing96/CurrentMood, pull requests merged in 2022-11, with the labels that each got.

#1 FIX : timezone 수정 [김태현]
  config/settings.py
Labels: ⚙ Setting

#2 DOCS : 베이스 템플릿 수정 테스트[유순일]
  main/templates/main/index.html
Labels: ✅ Test, 📃 Docs

#3 feat : articles CRUD [김태현]
  articles/forms.py
  articles/migrations/0001_initial.py
  articles/migrations/0002_remove_article_user.py
  articles/models.py
  articles/templates/articles/create.html
  articles/templates/articles/detail.html
  articles/templates/articles/index.html
  articles/templates/articles/update.html
  articles/urls.py
  articles/views.py
  config/settings.py
  main/templates/main/base.html
  main/templates/main/index.html
  main/urls.py
  main/views.py
Labels: ✨ Feature

#4 fix : articles를 루트 주소로 변경 [김태현]
  config/urls.py
Labels: 🐞 BugFix

#6 feat : accounts app 회원가입,정보수정,회원탈퇴 기능 추가 [이동현]
  accounts/forms.py
  accounts/migrations/0001_initial.py
  accounts/migrations/0002_auto_20221129_1554.py
  accounts/migrations/0003_auto_20221129_1655.py
  accounts/models.py
  accounts/templates/accounts/detail.html
  accounts/templates/accounts/index.html
  accounts/templates/accounts/login.html
  accounts/templates/accounts/signup.html
  accounts/templates/accounts/update.html
  accounts/urls.py
  accounts/views.py
  config/settings.py
Labels: ✨ Feature

#7 feat : 유튜브 검색 & 재생 기능 추가 [김선교]
  .DS_Store
  main/templates/main/test.html
  main/urls.py
  main/views.py
Labels: ✨ Feature

#8 feat : 재생 목록 기능 추가 [김선교]
  main/templates/main/test.html
  main/templates/main/test2.html
  main/urls.py
  main/views.py
Labels: ✨ Feature

#9 Dh 02 - accounts app 이미지업로드, 팔로우, 팔로잉 기능
  .gitignore
  accounts/forms.py
  accounts/migrations/0004_user_user_img.py
  accounts/migrations/0005_alter_user_user_img.py
  accounts/migrations/0006_user_followings.py
  accounts/models.py
  accounts/templates/accounts/detail.html
  accounts/templates/accounts/index.html
  accounts/templates/accounts/login.html
  accounts/templates/accounts/signup.html
  accounts/templates/accounts/update.html
  accounts/urls.py
  accounts/views.py
  config/settings.py
  static/image/profile.jpg
Labels: 🔨 Refactor, ✨ Feature

#11 feat : 현재 재생중인 곡 표시 기능 추가 [김선교]
  .DS_Store
  main/templates/main/test2.html
Labels: ✨ Feature

#13 feat : 반응형 네비게이션바 구현[유순일]
  accounts/migrations/0001_initial.py
  accounts/migrations/0002_auto_20221129_1554.py
  accounts/migrations/0003_auto_20221129_1655.py
  accounts/migrations/0004_user_user_img.py
  accounts/migrations/0005_alter_user_user_img.py
  accounts/migrations/0006_user_followings.py
  articles/migrations/0001_initial.py
  articles/migrations/0002_remove_article_user.py
  main/templates/main/base.html
  static/css/style.css
  static/js/script.js
Labels: 🎨 Html&css

#14 feat : base.html 수정 [김태현]
  articles/templates/articles/index.html
  articles/templates/articles/private.html
  articles/urls.py
  articles/views.py
  images/images/1b8296c37422e8d37798742dccf29718.jpg
  images/images/34859.jpg
  main/templates/main/base.html
  static/css/style.css
  static/image/album.png
Labels: 🎨 Html&css, ✨ Feature, ⚙ Setting
