Repository unboxing96/CurrentMood, pull requests merged in 2022-12, with the labels that each got.

#19 feat : 내 정보에서 작성한 글 목록 확인 기능 [이동현]
  accounts/templates/accounts/index.html
  accounts/templates/accounts/my_sharedmusiclist.html
  accounts/templates/accounts/mypage.html
  accounts/templates/accounts/popular.html
  accounts/urls.py
  accounts/views.py
  articles/forms.py
  articles/migrations/0002_place.py
  articles/migrations/0003_auto_20221201_1010.py
  articles/migrations/0004_article_place.py
  articles/migrations/0005_auto_20221201_1120.py
  articles/models.py
  articles/templates/articles/detail.html
  articles/templates/articles/index.html
  articles/views.py
Labels: 🔨 Refactor, ✨ Feature

#20 FEAT : 메인프라이빗 [김태현]
  accounts/migrations/0001_initial.py
  articles/templates/articles/private.html
  articles/templates/articles/test.html
  articles/urls.py
  articles/views.py
  images/images/KakaoTalk_20221129_114959848_03.jpg
  main/templates/main/base.html
  static/css/articles.css
Labels: 🎨 Html&css, ✨ Feature

#21 feat : 동영상 검색 & 썸네일 불러오기 & 재생 목록 추가 기능 구현 [김선교]
  main/templates/main/test3.html
  main/urls.py
  main/views.py
Labels: ✨ Feature

#22 style : 전체 폰트 컬러 white [김태현]
  articles/templates/articles/test.html
  main/templates/main/base.html
  static/css/articles.css
Labels: 🎨 Html&css

#23 refact : 네브바 로그인, 로그아웃 상태에따라 변경되게 수정 [이동현]
  accounts/views.py
  main/templates/main/base.html
Labels: 🔨 Refactor

#24 feat : 프로필 뮤직 추가/수정 기능 추가 [김선교]
  accounts/migrations/0001_initial.py
  accounts/migrations/0002_auto_20221201_1447.py
  accounts/models.py
  accounts/templates/accounts/my_sharedmusiclist.html
  accounts/templates/accounts/mypage.html
  accounts/templates/accounts/profile_music.html
  accounts/urls.py
  accounts/views.py
  main/templates/main/test3.html
Labels: ✨ Feature

#28 merge : TH-03 [김태형]
  articles/templates/articles/locations.html
  articles/templates/articles/public.html
  articles/views.py
  requirements.txt
Labels: ✨ Feature

#30 FEAT : 메인에 index로 넘어가는 버튼 추가
  articles/templates/articles/private.html
  static/css/articles.css
Labels: 🎨 Html&css

#31 feat : 게시글 좋아요 기능 [이동현]
  accounts/templates/accounts/detail.html
  accounts/templates/accounts/my_likedmusiclist.html
  accounts/templates/accounts/mypage.html
  accounts/urls.py
  accounts/views.py
  articles/forms.py
  articles/migrations/0006_article_like_users.py
  articles/migrations/0007_like_likeitem.py
  articles/migrations/0008_rename_likeitem_likesong.py
  articles/models.py
  articles/templates/articles/detail.html
  articles/templates/articles/index.html
  articles/urls.py
  articles/views.py
Labels: 🔨 Refactor, ✨ Feature

#35 feat : 좋아요한 글 목록 페이지 [이동현]
  accounts/templates/accounts/index.html
  accounts/templates/accounts/my_likedmusiclist.html
  accounts/templates/accounts/mypage.html
  accounts/views.py
  articles/migrations/0009_auto_20221202_1410.py
  articles/models.py
  articles/templates/articles/detail.html
  articles/views.py
  main/templates/main/base.html
Labels: ✨ Feature

#37 FEAT : articles/index 댓글 추기 [김태현]
  articles/admin.py
  articles/forms.py
  articles/migrations/0006_comment.py
  articles/migrations/0009_merge_0006_comment_0008_rename_likeitem_likesong.py
  articles/migrations/0010_auto_20221202_1414.py
  articles/models.py
  articles/templates/articles/detail.html
  articles/templates/articles/private.html
  articles/urls.py
  articles/views.py
  main/admin.py
  static/css/articles.css
Labels: ✨ Feature

#38 merge : TH-04
  articles/models.py
  articles/place_choose.py
  articles/recommend_place.py
  articles/templates/articles/locations.html
  articles/urls.py
  articles/views.py
  requirements.txt
Labels: ✨ Feature

#40 feat : Song 모델 추가 [김선교]
  accounts/migrations/0001_initial.py
  accounts/migrations/0002_auto_20221201_1447.py
  accounts/models.py
  accounts/templates/accounts/profile_music.html
  accounts/views.py
  articles/migrations/0001_initial.py
  articles/migrations/0002_place.py
  articles/migrations/0003_auto_20221201_1010.py
  articles/migrations/0004_article_place.py
  articles/migrations/0005_auto_20221201_1120.py
  main/migrations/0001_initial.py
  main/models.py
  main/templates/main/base.html
Labels: ✨ Feature

#45 test : 커스텀 미들웨어 부분 수정 [김선교]
  main/custom_middleware.py
  main/templates/main/base.html
Labels: ✅ Test

#46 PR : TH-05
  articles/place_choose.py
  articles/recommend_place.py
  articles/templates/articles/locationXMLrequest.html
  articles/templates/articles/locations.html
  articles/views.py
Labels: 🔨 Refactor

#49 feat : Song model 이미지 필드 추가 [김선교]
  accounts/migrations/0001_initial.py
  accounts/templates/accounts/profile_music.html
  accounts/views.py
  main/migrations/0001_initial.py
  main/models.py
  main/templates/main/base.html
Labels: ✨ Feature

#50 style : 메인 프라이빗 댓글 [김태현]
  articles/templates/articles/private.html
  articles/views.py
  images/images/KakaoTalk_20221129_114959848_03_C908ZDM.jpg
  images/images/ab0b5f8f79c22ba3750c7fca82c56b32.jpg
  images/images/pink-ear-muffs-12357734-removebg-preview.jpg
  images/images/png-clipart-christmas-s-pink-and-black-earmuffs-thumbnail-removebg-preview.jpg
  images/images/rest-roy-fielding-removebg-preview-0-Enhanced-Animated.mp4_000002450-removebg-preview.jpg
Labels: 🎨 Html&css

#51 feat : 프로필 뮤직 재생 & 세션 데이터 넘겨주기 기능 추가 [김선교]
  accounts/templates/accounts/profile_music.html
  main/templates/main/base.html
Labels: ✨ Feature

#54 feat : articles/detail 댓글 비동기 [김태현]
  articles/migrations/0002_comment_user.py
  articles/models.py
  articles/templates/articles/detail.html
  articles/views.py
  main/templates/main/base.html
Labels: ✨ Feature

#55 feat : Article create 수정 & 모델 수정 [김선교]
  articles/forms.py
  articles/migrations/0002_auto_20221205_1356.py
  articles/models.py
  articles/templates/articles/create.html
  articles/templates/articles/detail.html
  articles/urls.py
  articles/views.py
  config/settings.py
  main/custom_middleware.py
  main/models.py
Labels: ✨ Feature

#58 fix : 마이그레이션 초기화 [김선교]
  accounts/migrations/0001_initial.py
  articles/migrations/0001_initial.py
  articles/migrations/0002_auto_20221205_1356.py
  articles/migrations/0002_comment_user.py
  articles/templates/articles/index.html
  main/migrations/0001_initial.py
  main/templates/main/base.html
Labels: 🐞 BugFix

#59 fix : 배포 오류 수정중 [이동현]
  config/settings.py
Labels: 🐞 BugFix, 🌏 Deploy

#60 fix : 로컬 DB 존재하지 않는 부분 추가 [김선교]
  config/settings.py
Labels: 🐞 BugFix

#62 merge : TH-06 [김태형]
  articles/gmap.py
  articles/place_by_wifi.py
  articles/place_choose.py
  articles/static/articles/style.css
  articles/templates/articles/locations.html
  articles/views.py
  main/templates/main/base.html
  static/js/location.js
Labels: ✨ Feature

#63 feat : 게시글 노래 재생 기능 추가 [김선교]
  accounts/templates/accounts/mypage.html
  accounts/templates/accounts/profile_music.html
  articles/templates/articles/create.html
  articles/templates/articles/detail.html
  main/templates/main/base.html
Labels: ✨ Feature

#64 feat : index 페이지 대폭 수정 [김선교]
  articles/templates/articles/index.html
  articles/views.py
  main/templates/main/base.html
Labels: ✨ Feature

#65 style : 댓글 토글 추가
  articles/templates/articles/private.html
  articles/views.py
  main/templates/main/base.html
  static/css/articles.css
Labels: 🎨 Html&css

#67 fix : 배포 오류 수정 [이동현]
  .ebextensions/django.config
  .github/workflows/deploy.yml
  accounts/migrations/0001_initial.py
  articles/migrations/0001_initial.py
  config/settings.py
  config/urls.py
  main/migrations/0001_initial.py
Labels: 🐞 BugFix, 🌏 Deploy

#68 fix : 배포 오류 수정 [이동현]
  config/settings.py
Labels: 🐞 BugFix, 🌏 Deploy

#69 fix : 배포 오류 DB 수정중 [이동현]
  config/settings.py
Labels: 🐞 BugFix, 🌏 Deploy

#70 fix : 배포 두번뜨는 것 코드 수정 [이동현]
  .github/workflows/deploy.yml
Labels: 🐞 BugFix, 🌏 Deploy

#71 refact : 배포시 DB 반영 안되게 수정 [이동현]
  config/settings.py
Labels: 🐞 BugFix, 🌏 Deploy

#72 style : admin 계정 생성 [이동현]
  config/settings.py
Labels: 🔨 Refactor

#73 feat : 하단 바 플레이어 기능 수정 [김선교]
  articles/templates/articles/index.html
  main/templates/main/base.html
Labels: ✨ Feature

#74 style : 어드민 계정 생성 [이동현]
  config/settings.py
Labels: 🌏 Deploy

#75 style : 어드민 계정 생성 [이동현]
  config/settings.py
Labels: 🌏 Deploy

#76 fix : 인덱스페이지 글쓰기 위한 코드 [이동현]
  articles/templates/articles/create.html
  config/settings.py
Labels: 🐞 BugFix, 🌏 Deploy

#77 feat : 프로필 뮤직 css 수정, 팔로우버튼 추가 [유순일]
  accounts/migrations/0001_initial.py
  accounts/templates/accounts/detail.html
  accounts/templates/accounts/mypage.html
  accounts/templates/accounts/profile_music.html
  articles/migrations/0001_initial.py
  main/migrations/0001_initial.py
  static/css/accounts.css
Labels: 🎨 Html&css, ✨ Feature

#78 fix : 프로필 뮤직 부분 수정 [김선교]
  accounts/templates/accounts/mypage.html
  main/templates/main/base.html
Labels: ✨ Feature

#80 style : admin 페이지 수정 [김선교]
  main/admin.py
  main/templates/main/base.html
Labels: ✨ Feature

#82 PR : TH-07 [김태형]
  articles/gmap.py
  articles/templates/articles/locationXMLrequest.html
  articles/templates/articles/locations.html
  articles/views.py
  main/templates/main/base.html
Labels: 🔨 Refactor, ✨ Feature

#83 style : 하단 플레이어 디자인 수정 [김선교]
  main/templates/main/base.html
Labels: 🎨 Html&css

#84 feat : 하단 바 플레이어 슬라이드 모션 기능 추가 [김선교]
  main/templates/main/base.html
Labels: ✨ Feature

#85 test : 터치 이벤트 테스트 코드 추가 [김선교]
  main/templates/main/base.html
Labels: ✅ Test

#86 feat : 하단 바 플레이어 모바일 슬라이드 모션 추가 [김선교]
  main/templates/main/base.html
Labels: ✨ Feature

#88 feat : 하단 플레이어 이미지 클릭시 개별 노래 페이지로 연결하는 기능 구현 [김선교]
  articles/templates/articles/song.html
  articles/urls.py
  articles/views.py
  main/templates/main/base.html
Labels: ✨ Feature

#89 feat : 프로필 이미지 디폴트 추가 [김태현]
  accounts/migrations/0002_alter_user_user_img.py
  accounts/migrations/0003_alter_user_user_img.py
  accounts/models.py
  articles/migrations/0002_alter_article_image.py
  articles/migrations/0003_alter_article_image.py
  articles/models.py
  articles/templates/articles/index.html
  articles/templates/articles/private.html
  articles/views.py
  main/templates/main/base.html
  static/css/articles.css
  static/css/base.css
Labels: ✨ Feature

#91 style: 로컬 작업용 [김태현]
  static/css/base.css
Labels: 🎨 Html&css

#94 style : articles/public [김태현]
  articles/templates/articles/public.html
  main/templates/main/base.html
  static/css/articles.css
  static/css/base.css
Labels: 🎨 Html&css

#95 feat : 플레이리스트 확인하고 조작할 수 있는 기능 추가 [김선교]
  articles/templates/articles/song.html
  articles/templates/articles/song_detail.html
  articles/urls.py
  articles/views.py
  main/templates/main/base.html
Labels: ✨ Feature

#97 deploy : DB 배포를 위한 커밋 [이동현]
  accounts/migrations/0004_alter_user_user_img.py
  config/settings.py
  main/templates/main/base.html
Labels: 🌏 Deploy

#98 deploy : DB 배포 안되게 세팅즈 코드 수정 [이동현]
  config/settings.py
Labels: 🌏 Deploy

#99 style : 내 정보 페이지에서 뒤로가기 삭제 [이동현]
  accounts/templates/accounts/mypage.html
  main/templates/main/base.html
Labels: 🔨 Refactor

#101 fix : 도메인 400 에러 수정 [이동현]
  config/settings.py
Labels: 🐞 BugFix, 🌏 Deploy

#102 feat : 플레이리스트 스크롤 기능 추가 [김선교]
  articles/templates/articles/song.html
  main/templates/main/base.html
Labels: ✨ Feature

#105 style : song page 모바일 기준 디자인 수정 [김선교]
  articles/templates/articles/song.html
  main/templates/main/base.html
Labels: 🎨 Html&css

#108 style : static/image/bluebottle.jpeg 이미지 삭제
  static/image/ bluebottle.jpeg
Labels: 🎨 Html&css

#110 feat : 보관함 기능 추가 [김선교]
  accounts/templates/accounts/mylist.html
  articles/models.py
  main/templates/main/base.html
Labels: ✨ Feature

#111 style : 재생 목록 버튼 수정중 [김태현]
  articles/templates/articles/private.html
  articles/templates/articles/song.html
  main/templates/main/base.html
  static/image/speech-bubble.png
Labels: 🎨 Html&css

#112 feat : article update & delete 수정 완료 [김선교]
  articles/migrations/0005_remove_article_image.py
  articles/templates/articles/update.html
  articles/views.py
Labels: ✨ Feature

#113 feat : article에서 음악 클릭 시 재생 기능 추가 [김선교]
  articles/templates/articles/detail.html
  main/templates/main/base.html
Labels: ✨ Feature

#114 style : 재생 목록 스타일 되돌리기 [김태현]
  articles/templates/articles/song.html
Labels: 🎨 Html&css

#115 style : 재생 목록 스타일 되돌리기2 [김태현]
  articles/templates/articles/private.html
Labels: 🎨 Html&css

#117 style : song css 수정 [김선교]
  articles/templates/articles/song.html
  static/css/articles.css
  static/css/base.css
Labels: 🎨 Html&css

#118 feat : 게시글 상세페이지 좋아요 비동기 기능 [이동현]
  articles/templates/articles/detail.html
  articles/views.py
Labels: ✨ Feature

#119 deploy : migrate 적용을 위한 커밋 [이동현]
  config/settings.py
Labels: 🌏 Deploy

#122 fix : youtube api 액세스 초과해서 api key 교체 [김선교]
  accounts/templates/accounts/profile_music.html
  articles/templates/articles/create.html
  articles/templates/articles/update.html
Labels: 🐞 BugFix

#123 fix : favicon 에러메시지 해결 [유순일]
  main/templates/main/base.html
  static/css/accounts.css
Labels: 🐞 BugFix

#124 feat : article update시 노래 선택 없어도 되도록 기능 개선 [김선교]
  accounts/templates/accounts/detail.html
  articles/templates/articles/detail.html
  articles/templates/articles/update.html
  articles/views.py
Labels: ✨ Feature

#125 style : articles/private 댓글 수정 중 [김태현]
  articles/templates/articles/private.html
  main/templates/main/base.html
  static/css/articles.css
  static/image/location.png
Labels: 🎨 Html&css

#126 PR : TH-09 [김태형]
  articles/gmap.py
  articles/templates/articles/locationInputTest.html
  articles/templates/articles/locations.html
  articles/urls.py
  articles/views.py
  main/templates/main/base.html
  static/js/gps.js
  static/js/location.js
Labels: ✅ Test, 🔨 Refactor, ✨ Feature

#127 feat : 메인페이지 댓글창에 좋아요 비동기 추가 [이동현]
  accounts/views.py
  articles/templates/articles/private.html
Labels: ✨ Feature

#128 feat : song img 클릭시 create 기능 추가 (임시) [김선교]
  articles/templates/articles/song.html
  articles/templates/articles/song_detail.html
  static/css/articles.css
Labels: ✨ Feature

#129 fix : 내 정보에서 이미지 안보이는 버그 수정 [이동현]
  accounts/templates/accounts/mypage.html
  accounts/urls.py
  articles/templates/articles/private.html
  config/settings.py
  config/urls.py
Labels: 🐞 BugFix

#130 feat : 프로필 사진 필요한 부분 수정 & 사연 디테일 댓글 부분 수정 [김선교]
  articles/templates/articles/detail.html
  articles/templates/articles/song_detail.html
  main/templates/main/base.html
Labels: 🐞 BugFix, 🎨 Html&css, ✨ Feature

#131 fix : 팔로잉, 팔로우 버그 해결 [유순일]
  accounts/forms.py
  accounts/migrations/0007_alter_user_user_img.py
  accounts/models.py
  accounts/templates/accounts/detail.html
  accounts/templates/accounts/followerlist.html
  accounts/templates/accounts/followlist.html
  accounts/templates/accounts/my_followerlist.html
  accounts/templates/accounts/my_followlist.html
  accounts/templates/accounts/signup.html
  accounts/views.py
  config/urls.py
  images/images/18594ad07a5bdd68643368b494d27346.jpg
  images/images/18594ad07a5bdd68643368b494d27346_CTjvTJU.jpg
  images/images/도비.jpg
  images/images/박선영.jpg
  static/css/accounts.css
Labels: 🐞 BugFix

#132 fix : 프로필사진 첨부 오류 해결 [유순일]
  accounts/migrations/0008_alter_user_user_img.py
  accounts/views.py
Labels: 🐞 BugFix

#133 refact : create & update axios에서 form으로 변경 [김선교]
  articles/templates/articles/create.html
  articles/templates/articles/update.html
  articles/views.py
Labels: 🔨 Refactor

#134 fix : create 제대로 되지 않던 문제 해결 [김선교]
  articles/templates/articles/song.html
  articles/views.py
Labels: 🐞 BugFix

#135 test : aws createsuperuser test [김선교]
  .ebextensions/django.config
Labels: ✅ Test, 🌏 Deploy

#136 fix : 배포 테스트 중 오류 수정 [김선교]
  .ebextensions/django.config
Labels: 🐞 BugFix

#137 fix: 배포 오류 수정 [김선교]
  .ebextensions/django.config
Labels: 🐞 BugFix

#138 style : song_detail [김태현]
  articles/templates/articles/detail.html
  articles/templates/articles/private.html
  articles/templates/articles/song_detail.html
  articles/views.py
  static/css/articles.css
Labels: 🎨 Html&css

#141 PR : TH-10 [김태형]
  articles/templates/articles/locations.html
  articles/views.py
  config/settings.py
  main/templates/main/base.html
  requirements.txt
  static/js/gps.js
  static/js/location.js
Labels: 🔨 Refactor, ✨ Feature

#142 Sg 46
  accounts/templates/accounts/mypage.html
  accounts/templates/accounts/profile_music.html
  config/settings.py
  main/migrations/0002_auto_20221209_1742.py
  main/models.py
Labels: 🐞 BugFix

#144 style: song_detail 수정 중 [김태현]
  accounts/migrations/0001_initial.py
  accounts/migrations/0002_alter_user_user_img.py
  accounts/migrations/0003_alter_user_user_img.py
  accounts/migrations/0004_alter_user_user_img.py
  accounts/migrations/0005_alter_user_user_img.py
  accounts/migrations/0006_alter_user_user_img.py
  accounts/migrations/0007_alter_user_user_img.py
  accounts/migrations/0008_alter_user_user_img.py
  articles/migrations/0001_initial.py
  articles/migrations/0002_alter_article_image.py
  articles/migrations/0003_alter_article_image.py
  articles/migrations/0004_auto_20221207_2258.py
  articles/migrations/0005_remove_article_image.py
  articles/templates/articles/detail.html
  articles/templates/articles/song_detail.html
  main/migrations/0001_initial.py
  main/migrations/0002_auto_20221209_1742.py
  static/css/articles.css
Labels: 🎨 Html&css

#152 style : song_detail
  articles/templates/articles/private.html
  articles/templates/articles/song_detail.html
  articles/views.py
  main/migrations/0001_initial.py
  main/migrations/0002_song_maxresdefault.py
  main/models.py
  main/templates/main/base.html
  static/css/articles.css
  static/css/base.css
  static/image/bbibbi.jpg
Labels: 🎨 Html&css

#156 fix: main_model 수정 maxresdefault [김태현]
  main/models.py
Labels: 🐞 BugFix

#159 fix : 서버 에러 수정 [이동현]
  main/migrations/0003_song_maxresdefault.py
Labels: 🐞 BugFix, 🌏 Deploy

#160 fix : 서버 에러 수정중 [이동현]
  main/migrations/0003_song_maxresdefault.py
Labels: 🐞 BugFix, 🌏 Deploy

#164 refact : 회원가입, 회원수정에 성 제외 [이동현]
  accounts/forms.py
  accounts/migrations/0002_alter_user_last_name.py
  accounts/models.py
  accounts/templates/accounts/signup.html
  accounts/templates/accounts/update.html
  config/settings.py
Labels: 🔨 Refactor

#165 refact : DEBUG 값 수정 [이동현]
  config/settings.py
Labels: 🐞 BugFix, 🌏 Deploy

#166 feat : 플레이리스트 페이지 구현 [김선교]
  accounts/templates/accounts/mypage.html
  accounts/templates/accounts/playlist.html
  accounts/templates/accounts/profile_music.html
  accounts/urls.py
  accounts/views.py
  main/templates/main/base.html
  static/css/base.css
Labels: ✨ Feature

#168 fix : base.html js 수정 [김선교]
  main/templates/main/base.html
Labels: 🐞 BugFix

#169 feat : song_detail 비동기 좋아요 수정 중 [김태현]
  accounts/migrations/0002_user_like_song.py
  accounts/migrations/0003_remove_user_like_song.py
  accounts/models.py
  articles/templates/articles/song_detail.html
  articles/urls.py
  articles/views.py
  config/settings.py
  main/migrations/0005_song_like_users.py
  main/models.py
  main/templates/main/base.html
Labels: ✨ Feature

#171 refact : 사연 좋아요 -> 곡 좋아요 변경 [이동현]
  accounts/migrations/0004_merge_20221212_1447.py
  accounts/templates/accounts/mypage.html
  articles/templates/articles/song_detail.html
  articles/urls.py
  articles/views.py
  main/urls.py
  main/views.py
Labels: 🔨 Refactor

#174 fix : 내 정보 페이지화면 오류 수정 [이동현]
  accounts/templates/accounts/mypage.html
Labels: 🐞 BugFix

#175 fix : 내 정보 페이지화면 오류 수정 [이동현]
  accounts/templates/accounts/mypage.html
Labels: 🐞 BugFix

#177 feat : create_test 페이지 통해서 글 생성 기능 추가 [김선교]
  articles/templates/articles/create_test.html
  articles/templates/articles/detail.html
  articles/urls.py
  articles/views.py
  main/templates/main/base.html
Labels: ✨ Feature

#178 PR : 지도 좌표 가져오는 방식 변경 [김태형]
  main/templates/main/base.html
  static/js/location.js
Labels: ✨ Feature

#181 style : articles/private [김태현]
  accounts/migrations/0004_merge_20221212_1448.py
  articles/templates/articles/private.html
  static/css/articles.css
Labels: ✨ Feature

#182 test : 서버에러 확인을 위한 곡 좋아요 삭제 [이동현]
  accounts/migrations/0005_merge_20221213_0732.py
  articles/templates/articles/private.html
  articles/templates/articles/song_detail.html
Labels: ✅ Test

#183 test : song_detail 페이지에 좋아요 비동기x 추가 [이동현]
  articles/templates/articles/song_detail.html
  articles/views.py
Labels: ✅ Test

#184 test : song_detail 페이지 링크 뺀 하트만 넣음 [이동현]
  articles/templates/articles/song_detail.html
Labels: ✅ Test, ⚙ Setting

#185 test : song_detail 페이지 링크 다 뺀 하트 이모티콘만 넣음 [이동현]
  articles/templates/articles/song_detail.html
Labels: ✅ Test

#187 test : song_detail 페이지 하트 갯수 코드 빼고 하트 좋아요 기능 넣음 [이동현]
  articles/templates/articles/song_detail.html
Labels: ✅ Test

#188 test : song_detail 페이지 좋아요 비동기 코드 넣음 [이동현]
  articles/templates/articles/song_detail.html
  articles/views.py
Labels: ✅ Test

#190 test : song_detail 페이지 console.log 코드 추가 [이동현]
  articles/templates/articles/song_detail.html
Labels: ✅ Test

#192 feat : 현재 위치 기반 입력 기능 추가 [김선교]
  articles/templates/articles/create_test.html
Labels: ✨ Feature

#193 fix : base.html map.js 주석 처리 [김선교]
  articles/templates/articles/create.html
  main/templates/main/base.html
Labels: 🐞 BugFix

#194 style : song_detail 앨범 테두리 [김태현]
  accounts/migrations/0005_merge_20221213_0022.py
  accounts/migrations/0006_merge_20221213_0917.py
  articles/templates/articles/song_detail.html
  static/css/articles.css
Labels: 🎨 Html&css

#195 test : song_detail 페이지 테스트중 [이동현]
  articles/templates/articles/song_detail.html
Labels: ✅ Test

#196 deploy : 서버에 로컬 DB 반영 [이동현]
  config/settings.py
Labels: 🌏 Deploy

#197 fix : song_detail 페이지 서버 오류 수정중 [이동현]
  articles/templates/articles/song_detail.html
  config/settings.py
Labels: 🐞 BugFix

#198 fix : 내 정보 페이지 서버 오류 수정중 [이동현]
  accounts/templates/accounts/mypage.html
Labels: 🐞 BugFix

#201 update : 메인 페이지 위치별 게시물 가져오는 기능 수정중 [김태형]
  articles/views.py
Labels: ✨ Feature

#202 feat : 현재 위치 기반 create 기능 구현 완료 [김선교]
  articles/templates/articles/create.html
Labels: ✨ Feature

#203 feat : create form 현재위치 가져오는 방식 변경 [김태형]
  accounts/views.py
  main/templates/main/base.html
  static/js/gps.js
Labels: 🔨 Refactor, ✨ Feature

#204 feat : article update 페이지 지도 기능 수정 완료 [김선교]
  articles/templates/articles/create.html
  articles/templates/articles/update.html
Labels: ✨ Feature

#206 style : api 수정 [이동현]
  accounts/templates/accounts/profile_music.html
  articles/templates/articles/create.html
  articles/templates/articles/create_test.html
  articles/templates/articles/update.html
  articles/views.py
Labels: 🥰 Accessibility

#210 style : private, song_detail [김태현]
  articles/templates/articles/private.html
  articles/templates/articles/song.html
  articles/templates/articles/song_detail.html
  main/migrations/0006_auto_20221213_1354.py
  main/migrations/0007_auto_20221213_1740.py
  main/models.py
  main/templates/main/base.html
  static/css/articles.css
Labels: 🎨 Html&css

#211 feat : 지도 기능 구현 완료 [김선교]
  articles/templates/articles/create.html
  articles/templates/articles/private.html
  articles/templates/articles/song.html
  articles/templates/articles/update.html
  articles/views.py
  main/templates/main/base.html
Labels: ✨ Feature

#212 fix : song detail user_img 없을 시 발생하는 오류 해결 [김선교]
  articles/templates/articles/song_detail.html
Labels: 🐞 BugFix

#214 fix : 임시 페이지 링크 삭제 [김선교]
  articles/templates/articles/private.html
  articles/templates/articles/song_detail.html
  main/templates/main/base.html
Labels: ✨ Feature

#216 feat : JS 값 서버에 보내기 보완 [김태형]
  articles/gmap.py
  articles/templates/articles/create.html
  main/templates/main/base.html
  static/js/gps.js
Labels: 🐞 BugFix, 📬 API, 🔨 Refactor, ✨ Feature

#217 style : body, nabvar 등 패딩,마진 수정 [유순일]
  accounts/templates/accounts/mypage.html
  main/templates/main/base.html
  static/css/accounts.css
  static/css/base.css
Labels: 🎨 Html&css

#218 feat : 검색용 페이지 추가 [김선교]
  articles/templates/articles/index.html
  articles/views.py
Labels: ✨ Feature

#219 style : song_detail 기존 댓글 스타일로 [김태현]
  articles/templates/articles/song_detail.html
  static/css/articles.css
Labels: 🎨 Html&css

#220 deploy : 로컬 DB 반영 [이동현]
  config/settings.py
Labels: 🌏 Deploy

#221 deploy : DB 관련 코드 원복 [이동현]
  config/settings.py
Labels: 🌏 Deploy

#222 refact : private.py [김태형]
  articles/views.py
Labels: 🔨 Refactor

#225 fix : song_detail [김태현]
  articles/templates/articles/song_detail.html
Labels: 🎨 Html&css

#227 style : song_detail 사연 스타일 [김태현]
  accounts/migrations/0001_initial.py
  accounts/migrations/0002_alter_user_last_name.py
  accounts/migrations/0002_initial.py
  accounts/migrations/0002_user_like_song.py
  accounts/migrations/0003_remove_user_like_song.py
  accounts/migrations/0004_merge_20221212_1447.py
  accounts/migrations/0004_merge_20221212_1448.py
  accounts/migrations/0005_merge_20221213_0022.py
  accounts/migrations/0005_merge_20221213_0732.py
  accounts/migrations/0006_merge_20221213_0917.py
  articles/migrations/0001_initial.py
  articles/templates/articles/song_detail.html
  main/migrations/0001_initial.py
  main/migrations/0002_song_maxresdefault.py
  main/migrations/0003_song_maxresdefault.py
  main/migrations/0004_remove_song_maxresdefault.py
  main/migrations/0005_song_like_users.py
  main/migrations/0006_auto_20221213_1354.py
  main/migrations/0007_auto_20221213_1740.py
  static/css/articles.css
Labels: 🎨 Html&css

#228 feat : index 페이지 검색 기능 추가 [김선교]
  articles/templates/articles/index.html
  articles/views.py
Labels: ✨ Feature

#229 refact : 코드 정리 [김태형]
  articles/gmap.py
  articles/templates/articles/locationInputTest.html
  articles/urls.py
  articles/views.py
  main/templates/main/base.html
  static/js/gps.js
Labels: 🔨 Refactor

#234 style : 주소/accounts/ 에는 admin 계정만 접근 가능 [이동현]
  accounts/views.py
Labels: 🥰 Accessibility

#241 style : song_detail 완료 [김태현]
  articles/templates/articles/detail.html
  articles/templates/articles/song_detail.html
  static/css/articles.css
Labels: 🎨 Html&css

#247 style : 메인 캐러셀 [김태현]
  articles/templates/articles/private.html
  articles/views.py
  main/templates/main/base.html
Labels: 🎨 Html&css

#251 docs : README 작성 [이동현]
  README.md
Labels: 📃 Docs

#252 docs : 팀 리드미 준비 [김태현]
  README.md
Labels: 📃 Docs
